# Generated by Django 2.2.12 on 2020-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fn125tag",
            name="tagid",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
