# Generated by Django 2.2.12 on 2020-06-06 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0002_longer_tagid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn011',
            name='field_crew',
            field=models.ManyToManyField(related_name='fn_field_crew', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fn011',
            name='prj_ldr',
            field=models.ForeignKey(help_text='Project Lead', on_delete=django.db.models.deletion.CASCADE, related_name='fn_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fn123',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Species'),
        ),
        migrations.AlterField(
            model_name='subgear',
            name='grcol',
            field=models.CharField(blank=True, choices=[('6', 'Transparent'), ('8', 'Grey'), ('7', 'Other'), ('5', 'Discoloured White'), ('4', 'Blue'), ('2', 'Black'), ('1', 'White'), ('3', 'Green')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subgear',
            name='grknot',
            field=models.IntegerField(blank=True, choices=[(1, 'Knotless'), (3, 'other'), (2, 'Knots present')], null=True),
        ),
        migrations.AlterField(
            model_name='subgear',
            name='grmat',
            field=models.CharField(blank=True, choices=[('1', 'Polyamide (e.g. Nylon)'), ('6', 'Other'), ('3', 'Polyethylene'), ('5', 'Cotton'), ('2', 'Polypropylene (e.g. Ulstron)'), ('4', 'Polyester')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subgear',
            name='gryarn',
            field=models.IntegerField(blank=True, choices=[(2, 'Multifilament'), (3, 'no data'), (1, 'Monofilament')], null=True),
        ),
    ]
