# Generated by Django 2.2.12 on 2020-06-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0003_auto_20200606_0901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fn123",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fn_catch_counts",
                to="common.Species",
            ),
        ),
    ]
