# Generated by Django 2.2.23 on 2021-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0006_add_FN124'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn013',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fn014',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
