# Generated by Django 2.2.23 on 2021-06-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0008_fn013_fn014_populate_slugs'),
    ]

    operations = [
    ]
