# Generated by Django 2.2.23 on 2021-08-09 11:31

import django.db.models.deletion
from django.db import migrations, models


def fill_missing_slug(model):
    null_slug = model.objects.filter(slug__isnull=True)
    for item in null_slug:
        item.save()


def forwards_fn013(apps, schema_editor):
    model = apps.get_model("fn_portal", "fn013")
    fill_missing_slug(model)


def forwards_fn014(apps, schema_editor):
    model = apps.get_model("fn_portal", "fn014")
    fill_missing_slug(model)


def reverse_nullslug(apps, schema_editor):
    # no need to do anything here:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0009_fn013_fn014_unique_slug"),
    ]

    operations = [
        migrations.RunPython(forwards_fn013, reverse_nullslug),
        migrations.RunPython(forwards_fn014, reverse_nullslug),
        migrations.AlterModelOptions(
            name="fn122",
            options={"ordering": ("sample", "eff")},
        ),
        migrations.AlterModelOptions(
            name="fn123",
            options={"ordering": ("effort", "species", "grp")},
        ),
        migrations.AlterModelOptions(
            name="fn124",
            options={"ordering": ["catch", "siz"]},
        ),
        migrations.AlterModelOptions(
            name="fn125",
            options={"ordering": ["catch", "fish"]},
        ),
        # migrations.RemoveField(
        #     model_name="fn011",
        #     name="field_crew",
        # ),
        migrations.RemoveField(
            model_name="fn022",
            name="v0",
        ),
        migrations.RemoveField(
            model_name="fn026",
            name="aru",
        ),
        migrations.RemoveField(
            model_name="fn026",
            name="space_siz",
        ),
        migrations.AlterField(
            model_name="fn013",
            name="slug",
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="fn014",
            name="slug",
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="fn028",
            name="gr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modes",
                to="fn_portal.Gear",
            ),
        ),
    ]
