# Generated by Django 2.2.23 on 2021-08-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0010_update_fn0_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fn121',
            old_name='grid',
            new_name='grid5',
        ),
        migrations.AddField(
            model_name='fn121',
            name='crew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fn121',
            name='dd_lat1',
            field=models.FloatField(blank=True, null=True, verbose_name='End Latitude (dd)'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='dd_lon1',
            field=models.FloatField(blank=True, null=True, verbose_name='End Longitude (dd)'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='grdepmax',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Max. Gear Depth (m)'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='grdepmin',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Min. Gear Depth (m)'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='fn_portal.FN028'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='sitem0',
            field=models.FloatField(blank=True, null=True, verbose_name='Start Site Temperature (degrees C)'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='sitem1',
            field=models.FloatField(blank=True, null=True, verbose_name='End Site Temperature (degrees C)'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='sitp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Site Type'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='fn_portal.FN026'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='ssn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='fn_portal.FN022'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='xslime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='dd_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Start Latitude(dd)'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='dd_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Start Longitude (dd)'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='effdt0',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Effort Start Date'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='effdt1',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Effort End Date'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='effdur',
            field=models.FloatField(blank=True, null=True, verbose_name='Effort Duration (hours)'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='effst',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='Effort Status'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='efftm0',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Effort Start Date'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='efftm1',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Effort End Time'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='sidep',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Site Depth (m)'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Label'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='sitem',
            field=models.FloatField(blank=True, null=True, verbose_name='Site Temperature (degrees C)'),
        ),
    ]
