# Generated by Django 2.2.23 on 2021-08-31 16:06

from django.db import migrations


def populate_design_fks(apps, schema_editor):

    FN121 = apps.get_model("fn_portal", "FN121")
    FN022 = apps.get_model("fn_portal", "FN022")
    FN026 = apps.get_model("fn_portal", "FN026")
    FN028 = apps.get_model("fn_portal", "FN028")

    ssn_cache = {x.project_id: x for x in FN022.objects.all()}
    space_cache = {x.project_id: x for x in FN026.objects.all()}

    mode_cache = {
        f"{x.project_id}-{x.gr.gr_code}-{x.orient}-{x.gruse}": x
        for x in FN028.objects.select_related("gr").all()
    }

    samples = FN121.objects.all()
    for sample in samples:
        orient = sample.orient if sample.orient else "9"
        mode_key = f"{sample.project_id}-{sample.gr}-{orient}-1"
        mode = mode_cache.get(mode_key)
        if mode:
            sample.mode = mode

        ssn = ssn_cache.get(sample.project_id)
        if ssn:
            sample.ssn = ssn
            space = space_cache.get(sample.project_id)
        if space:
            sample.space = space
        sample.save()


class Migration(migrations.Migration):

    dependencies = [
        # ('fn_portal', '0020_fn123_comment_to_comment3'),
        ("fn_portal", "0011_update_fn121"),
    ]

    operations = [
        migrations.RunPython(populate_design_fks),
    ]
