# Generated by Django 2.2.23 on 2021-08-10 12:48

from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0012_gruse_orient_as_choice_fields"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.RunSQL(
            sql="""
            -- from https://dba.stackexchange.com/questions/110582/uniqueness-constraint-with-date-range
            -- the '[]' is inclusive: [1,2,3],[4,5,6] NOT [1,2,3),[3,4,5,6)

            ALTER TABLE fn_portal_fn022
            ADD CONSTRAINT unique_project_ssn_date0_ssn_date1
            EXCLUDE  USING gist
    	    ( project_id WITH =,
	            daterange(ssn_date0, ssn_date1, '[]') WITH &&
            );
            """,
            reverse_sql="""
            ALTER TABLE fn_portal_fn022
            DROP CONSTRAINT unique_project_ssn_date0_ssn_date1;
            ;
            """,
        ),
    ]
