# Generated by Django 2.2.23 on 2021-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0014_add_grtp_to_gear"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE fn_portal_gear
                   SET grtp = COALESCE(LEFT (gr_code,2),'UN')
                 WHERE grtp IS NULL;
            """
        ),
        migrations.AlterField(
            model_name="gear",
            name="grtp",
            field=models.CharField(
                db_index=True, max_length=2, verbose_name="Gear Type"
            ),
        ),
    ]
