# Generated by Django 2.2.23 on 2021-08-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0015_add_index_gear_grtp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fn028',
            old_name='gr',
            new_name='gear',
        ),
    ]
