# Generated by Django 2.2.23 on 2021-08-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0016_rename_fn028_gr_to_gear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn121',
            name='orient',
        ),
    ]
