# Generated by Django 2.2.23 on 2021-08-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0017_remove_orient_from_fn121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn121',
            name='gr',
        ),
        migrations.RemoveField(
            model_name='fn121',
            name='grtp',
        ),
    ]
