# Generated by Django 2.2.23 on 2021-08-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0019_updates_to_fn1_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fn123',
            old_name='comment',
            new_name='comment3',
        ),
    ]
