# Generated by Django 2.2.23 on 2021-09-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0020_fn123_comment_to_comment3'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnprotocol',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fnprotocol',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fnprotocol',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Protocol Description in markdown'),
        ),
        migrations.AddField(
            model_name='fnprotocol',
            name='description_html',
            field=models.TextField(blank=True, null=True, verbose_name='Protocol Description'),
        ),
        migrations.AlterField(
            model_name='subgear',
            name='grknot',
            field=models.IntegerField(blank=True, choices=[(1, 'Knotless'), (2, 'Knots present'), (3, 'other')], null=True),
        ),
    ]
