# Generated by Django 2.2.23 on 2021-09-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0021_fnprotocol_active_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnprotocol',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Is this protocol currently in use?'),
        ),
        migrations.AlterField(
            model_name='fnprotocol',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Has this protocol been documented?'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='gr_des',
            field=models.TextField(blank=True, null=True, verbose_name='Gear Description in markdown'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='gr_des_html',
            field=models.TextField(blank=True, null=True, verbose_name='Gear Description'),
        ),
        migrations.CreateModel(
            name='GearEffortProcessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('1', 'By Net'), ('2', 'By Mesh Size'), ('3', 'By Panel Group'), ('4', 'By Panel'), ('5', 'Other (TBD)')], default='1', max_length=2, verbose_name='Process type choice associated with this gear and effort.')),
                ('eff', models.CharField(default='001', max_length=3, verbose_name='Effort (EFF) value')),
                ('effdst', models.FloatField(blank=True, null=True, verbose_name='Effort Distance (m) associated with this gear and effort (optional)')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_types', to='fn_portal.Gear')),
            ],
            options={
                'verbose_name': 'Gear Process Type',
                'ordering': ['gear_id', 'process_type', 'eff'],
                'unique_together': {('gear', 'process_type', 'eff')},
            },
        ),
    ]
