# Generated by Django 2.2.23 on 2021-09-23 12:47


from django.db import migrations


def populate_gear_process_type(apps, schema_editor):
    """get all of our existing gears and add a default process type for each one."""

    Gear = apps.get_model("fn_portal", "Gear")
    GearEffortProcessType = apps.get_model("fn_portal", "GearEffortProcessType")

    gear_process_types = []
    gears = Gear.objects.all()
    for gear in gears:
        obj = GearEffortProcessType(gear=gear)
        gear_process_types.append(obj)
    GearEffortProcessType.objects.bulk_create(gear_process_types)


def clear_gear_process_type(apps, schema_editor):
    """get all of our existing gears and add a default process type for each one."""

    GearEffortProcessType = apps.get_model("fn_portal", "GearEffortProcessType")

    GearEffortProcessType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0022_add_gear_process_type"),
    ]

    operations = [
        migrations.RunPython(
            populate_gear_process_type, reverse_code=clear_gear_process_type
        )
    ]
