# Generated by Django 2.2.23 on 2021-10-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0024_ddlat_ddlon_to_dd_lat_dd_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geareffortprocesstype',
            name='process_type',
            field=models.CharField(choices=[('1', 'By Sample'), ('2', 'By Mesh Size'), ('3', 'By Panel Group'), ('4', 'By Panel'), ('5', 'Other (TBD)')], default='1', max_length=2, verbose_name='Process type choice associated with this gear and effort.'),
        ),
        migrations.CreateModel(
            name='ProjectGearProcessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('1', 'By Sample'), ('2', 'By Mesh Size'), ('3', 'By Panel Group'), ('4', 'By Panel'), ('5', 'Other (TBD)')], default='1', max_length=2, verbose_name='Process type choice associated with this gear.')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_gear_process_types', to='fn_portal.Gear')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_gear_process_types', to='fn_portal.FN011')),
            ],
        ),
    ]
