# Generated by Django 2.2.23 on 2021-11-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0026_project_gear_processtype_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fn011',
            options={'ordering': ['-year', 'prj_cd']},
        ),
        migrations.RemoveField(
            model_name='fn125_lamprey',
            name='lamijc',
        ),
        migrations.AlterField(
            model_name='projectgearprocesstype',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_process_types', to='fn_portal.Gear'),
        ),
        migrations.AlterField(
            model_name='projectgearprocesstype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_process_types', to='fn_portal.FN011'),
        ),
    ]
