# Generated by Django 2.2.23 on 2021-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0027_FN125Lamprey_drop_lamijc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn125',
            name='rwt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
