# Generated by Django 2.2.23 on 2021-11-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0028_FN125_RWT_as_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='gr_code',
            field=models.CharField(db_index=True, max_length=5, unique=True, verbose_name='Gear Code'),
        ),
    ]
