# Generated by Django 2.2.23 on 2021-12-08 17:22

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0029_increased_gear_code_to_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn121',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-81, 45), help_text='Represented as (longitude, latitude)', srid=4326),
        ),
    ]
