# Generated by Django 2.2.23 on 2021-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('common', '0006_fn123_comment_to_comment3'),
        ("fn_portal", "0031_populate__fn121_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="fn121",
            name="management_units",
            field=models.ManyToManyField(
                blank=True, related_name="fn121_samples", to="common.ManagementUnit"
            ),
        ),
    ]
