# Generated by Django 2.2.23 on 2022-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0032_fn121_management_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fn126',
            old_name='foodcnt',
            new_name='fdcnt',
        ),
        migrations.RenameField(
            model_name='fn126',
            old_name='foodval',
            new_name='fdval',
        ),
        migrations.AlterField(
            model_name='fn126',
            name='fdmes',
            field=models.CharField(blank=True, choices=[(None, 'No Data'), ('L', 'Length'), ('W', 'Weight'), ('V', 'Volume')], help_text='Food Measure Code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fn126',
            name='lf',
            field=models.CharField(blank=True, choices=[(None, 'No Data'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60')], help_text='Life Stage', max_length=2, null=True),
        ),
    ]
