# Generated by Django 2.2.23 on 2022-03-10 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0034_fn012_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn012',
            name='k_max_error',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(5.0)], verbose_name='Maximum K (FLEN) - error'),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='k_max_warn',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.07), django.core.validators.MaxValueValidator(4.0)], verbose_name='Maximum K (FLEN) - warning'),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='k_min_error',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(5.0)], verbose_name='Minimum K (TLEN) - error'),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='k_min_warn',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.07), django.core.validators.MaxValueValidator(4.0)], verbose_name='Minimum K (TLEN) - warning'),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='lamsam',
            field=models.CharField(choices=[('0', 'Not Collected'), ('1', 'XLAM (NO LONGER SUPPORTED)'), ('2', 'LAMIJC')], default='2', help_text='Lamprey Reporting', max_length=1),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='rwt_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(55000)], verbose_name='Maximum Round Weight (g)'),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='rwt_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(55000)], verbose_name='Minimum Round Weight (g)'),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='sizint',
            field=models.IntegerField(blank=True, help_text='Size Sample Interval (mm)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='k_max_error',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(5.0)], verbose_name='Maximum K (FLEN) - error'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='k_max_warn',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.07), django.core.validators.MaxValueValidator(4.0)], verbose_name='Maximum K (FLEN) - warning'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='k_min_error',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(5.0)], verbose_name='Minimum K (TLEN) - error'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='k_min_warn',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.07), django.core.validators.MaxValueValidator(4.0)], verbose_name='Minimum K (TLEN) - warning'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='lamsam',
            field=models.CharField(choices=[('0', 'Not Collected'), ('1', 'XLAM (NO LONGER SUPPORTED)'), ('2', 'LAMIJC')], default='2', help_text='Lamprey Reporting', max_length=1),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='rwt_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(55000)], verbose_name='Maximum Round Weight (g)'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='rwt_min',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(55000)], verbose_name='Minimum Round Weight (g)'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='sizint',
            field=models.IntegerField(blank=True, help_text='Size Sample Interval (mm)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
