# Generated by Django 2.2.23 on 2022-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0034_fn012_and_fn012Defaults_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fn011',
            options={'ordering': ['-year', 'prj_cd'], 'verbose_name_plural': 'FN011 - Projects'},
        ),
        migrations.AlterModelOptions(
            name='fn012',
            options={'verbose_name_plural': 'FN012 - Project Sampling Specs'},
        ),
        migrations.AlterModelOptions(
            name='fn012default',
            options={'verbose_name_plural': 'FN012Defaults - Protocol Sampling Specs'},
        ),
        migrations.AlterField(
            model_name='fn012',
            name='agedec1',
            field=models.CharField(choices=[('0', 'No structures sampled'), ('1', 'Scales (any side)'), ('2', 'Scales (left side)'), ('3', 'Scales (right side)'), ('4', 'Pectoral ray'), ('5', 'Pectoral spine'), ('6', 'Pelvic ray'), ('7', 'Dorsal spine'), ('A', 'Otolith'), ('B', 'Operculum'), ('C', 'Sub-operculum'), ('D', 'Cleithrum'), ('E', 'Centrum'), ('F', 'Branchiostegal'), ('G', 'Other (NO LONGER SUPPORTED)'), ('M', 'Maxilla'), ('T', 'Tag'), ('V', 'Vertebrate'), ('X', 'Methods vary across fish')], default='0', help_text='Age Method', max_length=1),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='agedec2',
            field=models.CharField(blank=True, choices=[('0', 'Not validated'), ('1', 'Validated')], help_text='Age Method', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='fdsam2',
            field=models.CharField(blank=True, choices=[('1', 'Fish Community and Habitat Section (FCH), Fisheries Branch'), ('2', 'Haliburton Hastings Fisheries Assessment Unit'), ('3', 'Other')], help_text='FDSAM Taxon Coding Scheme', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='grp_des',
            field=models.CharField(default='Default Group', help_text='The meaning of a GRP code or more general information about SPC+GRP.', max_length=300),
        ),
        migrations.AlterField(
            model_name='fn012default',
            name='agedec1',
            field=models.CharField(choices=[('0', 'No structures sampled'), ('1', 'Scales (any side)'), ('2', 'Scales (left side)'), ('3', 'Scales (right side)'), ('4', 'Pectoral ray'), ('5', 'Pectoral spine'), ('6', 'Pelvic ray'), ('7', 'Dorsal spine'), ('A', 'Otolith'), ('B', 'Operculum'), ('C', 'Sub-operculum'), ('D', 'Cleithrum'), ('E', 'Centrum'), ('F', 'Branchiostegal'), ('G', 'Other (NO LONGER SUPPORTED)'), ('M', 'Maxilla'), ('T', 'Tag'), ('V', 'Vertebrate'), ('X', 'Methods vary across fish')], default='0', help_text='Age Method', max_length=1),
        ),
        migrations.AlterField(
            model_name='fn012default',
            name='agedec2',
            field=models.CharField(blank=True, choices=[('0', 'Not validated'), ('1', 'Validated')], help_text='Age Method', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fn012default',
            name='fdsam2',
            field=models.CharField(blank=True, choices=[('1', 'Fish Community and Habitat Section (FCH), Fisheries Branch'), ('2', 'Haliburton Hastings Fisheries Assessment Unit'), ('3', 'Other')], help_text='FDSAM Taxon Coding Scheme', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fn012default',
            name='grp_des',
            field=models.CharField(default='Default Group', help_text='The meaning of a GRP code or more general information about SPC+GRP.', max_length=300),
        ),
    ]
