# Generated by Django 2.2.23 on 2022-03-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0036_rename_fn012Default_to_FN012Protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn012',
            name='flen2tlen_alpha',
        ),
        migrations.RemoveField(
            model_name='fn012',
            name='flen2tlen_beta',
        ),
        migrations.RemoveField(
            model_name='fn012protocol',
            name='flen2tlen_alpha',
        ),
        migrations.RemoveField(
            model_name='fn012protocol',
            name='flen2tlen_beta',
        ),
        migrations.AlterField(
            model_name='fn012',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_specs', to='fn_portal.FN011'),
        ),
        migrations.AlterField(
            model_name='fn012',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fn012_sample_specs', to='common.Species'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='lake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_specs', to='common.Lake'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_specs', to='fn_portal.FNProtocol'),
        ),
        migrations.AlterField(
            model_name='fn012protocol',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fn012protocol_sample_specs', to='common.Species'),
        ),
    ]
