# Generated by Django 2.2.23 on 2022-03-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0037_remove_flen2tlen_from_fn012_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn012',
            name='lamsam',
            field=models.CharField(choices=[('0', 'Not Collected'), ('1', 'XLAM (NO LONGER SUPPORTED)'), ('2', 'LAMIJC')], default=2, help_text='Lamprey Reporting', max_length=1),
        ),
        migrations.AddField(
            model_name='fn012protocol',
            name='lamsam',
            field=models.CharField(choices=[('0', 'Not Collected'), ('1', 'XLAM (NO LONGER SUPPORTED)'), ('2', 'LAMIJC')], default=2, help_text='Lamprey Reporting', max_length=1),
        ),
    ]
