# Generated by Django 2.2.23 on 2022-03-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0038_add_fn012_lammrk"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
          -- initial values of FN012Protocol table
            INSERT INTO fn_portal_fn012protocol
            (
              slug,
              lake_id,
              protocol_id,
              species_id,
              grp,
              grp_des,
              biosam,
              sizsam,
              sizatt,
              sizint,
              agedec1,
              fdsam1,
              spcmrk1,
              lamsam,
              flen_min,
              flen_max,
              tlen_min,
              tlen_max,
              rwt_min,
              rwt_max,
              k_min_error,
              k_min_warn,
              k_max_error,
              k_max_warn
            )
            SELECT DISTINCT
            lower('fn012protocol-' || common_lake.abbrev || '-' ||fnprotocol.abbrev || '-' || spc.spc || '-' || grp) as slug,
            common_lake.id AS lake_id,
                   fnprotocol.id AS protocol_id,
                   spc.id AS species_id,
                   grp,
                   'default group' AS grp_des,
                   '0' AS biosam,
                   '0' AS sizsam,
                   'flen' AS sizatt,
                   1 AS sizint,
                   '0' AS agedec1,
                   '0' AS fdsam1,
                   '0' AS spcmrk1,
                   '2' as lamsam,
                   flen_min,
                   flen_max,
                   tlen_min,
                   tlen_max,
                   rwt_min,
                   rwt_max,
                   k_min_error,
                   k_min_warn,
                   k_max_error,
                   k_max_warn
            FROM fn_portal_fn123 AS fn123
              JOIN common_species AS spc ON spc.id = fn123.species_id
              JOIN fn_portal_fn122 AS fn122 ON fn122.id = fn123.effort_id
              JOIN fn_portal_fn121 AS fn121 ON fn121.id = fn122.sample_id
              JOIN fn_portal_fn011 AS fn011 ON fn011.id = fn121.project_id
              JOIN common_lake ON common_lake.id = fn011.lake_id
              JOIN fn_portal_fnprotocol AS fnprotocol ON fnprotocol.id = fn011.protocol_id
            WHERE spc.spc NOT IN ('000','999','998')
            ORDER BY common_lake.id,
                     fnprotocol.id,
                     spc.id,
                     grp;
                        """,
            reverse_sql="DELETE FROM fn_portal_fn012protocol;",
        )
    ]
