# Generated by Django 3.2.12 on 2022-05-27 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0038_fn012_lake_protocol_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fn012",
            name="flen_min",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(750),
                ],
                verbose_name="Minimum Fork Length (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="fn012",
            name="rwt_min",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(55000),
                ],
                verbose_name="Minimum Round Weight (g)",
            ),
        ),
        migrations.AlterField(
            model_name="fn012",
            name="tlen_min",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(750),
                ],
                verbose_name="Minimum Total Length (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="fn012protocol",
            name="flen_min",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(750),
                ],
                verbose_name="Minimum Fork Length (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="fn012protocol",
            name="rwt_min",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(55000),
                ],
                verbose_name="Minimum Round Weight (g)",
            ),
        ),
        migrations.AlterField(
            model_name="fn012protocol",
            name="tlen_min",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(750),
                ],
                verbose_name="Minimum Total Length (mm)",
            ),
        ),
    ]
