# Generated by Django 3.2.12 on 2022-08-12 15:11

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0040_create_fn121Limno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn121',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-81, 45), help_text='Represented as (longitude, latitude)', srid=4326, verbose_name='Sample Point'),
        ),
        migrations.AddIndex(
            model_name='fn127',
            index=models.Index(fields=['fish', 'preferred'], name='fn_portal_f_fish_id_a2f5e0_idx'),
        ),
    ]
