# Generated by Django 3.2.12 on 2022-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0041_idx_fn127_fish_preferred'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fn127',
            constraint=models.UniqueConstraint(condition=models.Q(('preferred', True)), fields=('fish',), name='idx_fish_one_preferred_age'),
        ),
    ]
