# Generated by Django 3.2.12 on 2022-09-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0043_idx_fn127_fish_age_preferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn026',
            name='space',
            field=models.CharField(db_index=True, help_text='Space Code', max_length=4),
        ),
        migrations.CreateModel(
            name='FN026Subspace',
            fields=[
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subspace', models.CharField(db_index=True, help_text='Subspace Code', max_length=4)),
                ('subspace_des', models.CharField(help_text='Subspace Description', max_length=100)),
                ('grdep_ge', models.FloatField(blank=True, help_text='The lower limit of gear depth (in metres).', null=True)),
                ('grdep_lt', models.FloatField(blank=True, help_text='The upper limit of gear depth (in metres).', null=True)),
                ('sidep_ge', models.FloatField(blank=True, help_text='The upper depth limit (in metres) of sites that belong to the corresponding spatial stratum', null=True)),
                ('sidep_lt', models.FloatField(blank=True, help_text='The lower depth limit (in metres) of sites that belong to the corresponding spatial stratum. ', null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('dd_lat', models.FloatField(blank=True, null=True)),
                ('dd_lon', models.FloatField(blank=True, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_substrata', to='fn_portal.fn026')),
            ],
            options={
                'verbose_name': 'FN026Subspace - Spatial Substrata',
                'verbose_name_plural': 'FN026Subspace - Spatial Substrata',
                'ordering': ['subspace'],
            },
        ),
        migrations.AddConstraint(
            model_name='fn026subspace',
            constraint=models.UniqueConstraint(fields=('space', 'subspace'), name='unique_subspace_code'),
        ),
        migrations.AddConstraint(
            model_name='fn026subspace',
            constraint=models.UniqueConstraint(fields=('space', 'subspace_des'), name='unique_subspace_des'),
        ),
    ]
