# Generated by Django 3.2.12 on 2022-09-21 09:25

from django.db import migrations
from django.utils.text import slugify


def fill_subspaces_from_spaces(apps, schema_editor):
    FN026 = apps.get_model("fn_portal", "FN026")
    FN026Subspace = apps.get_model("fn_portal", "FN026Subspace")

    for space in FN026.objects.prefetch_related("project").all():

        raw_slug = "-".join([space.project.prj_cd, space.space, space.space])

        subspace, created = FN026Subspace.objects.get_or_create(
            space_id=space.id,
            subspace=space.space,
            subspace_des=space.space_des,
            slug=slugify(raw_slug),
        )

        subspace.grdep_ge = space.grdep_ge
        subspace.grdep_lt = space.grdep_lt
        subspace.sidep_ge = space.sidep_ge
        subspace.sidep_lt = space.sidep_lt
        subspace.dd_lat = space.dd_lat
        subspace.dd_lon = space.dd_lon

        subspace.save()


def unfill_subspaces(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0044_add_fn026subspace_table"),
    ]

    operations = [migrations.RunPython(fill_subspaces_from_spaces, unfill_subspaces)]
