# Generated by Django 3.2.12 on 2022-09-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0044_add_fn026subspace_table_squashed_0048_drop_fn121_space_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fn121',
            old_name='dd_lat',
            new_name='dd_lat0',
        ),
        migrations.RenameField(
            model_name='fn121',
            old_name='dd_lon',
            new_name='dd_lon0',
        ),
        migrations.RenameField(
            model_name='fn121',
            old_name='xslime',
            new_name='slime',
        ),
        migrations.RemoveField(
            model_name='fn121',
            name='secchi',
        ),
        migrations.RemoveField(
            model_name='fn121',
            name='sidep',
        ),
        migrations.AddField(
            model_name='fn121',
            name='secchi0',
            field=models.FloatField(blank=True, null=True, verbose_name='First Secchi Depth'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='sidep0',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Site Depth 0 (m)'),
        ),
        migrations.AddField(
            model_name='fn121',
            name='sidep1',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Site Depth 1 (m)'),
        ),
    ]
