# Generated by Django 3.2.12 on 2022-09-26 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0045_renamed_fn121_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fn121limno",
            old_name="xo2",
            new_name="o2bot0",
        ),
        migrations.RenameField(
            model_name="fn121limno",
            old_name="xo22",
            new_name="o2bot1",
        ),
        migrations.RenameField(
            model_name="fn121limno",
            old_name="surfdo2",
            new_name="o2surf0",
        ),
        migrations.RenameField(
            model_name="fn121limno",
            old_name="surfdo22",
            new_name="o2surf1",
        ),
        migrations.RenameField(
            model_name="fn125tag",
            old_name="xcwtseq",
            new_name="cwtseq",
        ),
        migrations.RunSQL(
            "UPDATE fn_portal_fn121 SET sitem0 = sitem WHERE sitem IS NOT NULL;", None
        ),
        migrations.RemoveField(
            model_name="fn121",
            name="sitem",
        ),
        migrations.RemoveField(
            model_name="fn121limno",
            name="do_gear",
        ),
        migrations.RemoveField(
            model_name="fn125tag",
            name="xtag_chk",
        ),
        migrations.RemoveField(
            model_name="fn125tag",
            name="xtaginckd",
        ),
        migrations.AddField(
            model_name="fn121",
            name="secchi1",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Second Secchi Depth"
            ),
        ),
        migrations.AddField(
            model_name="fn121limno",
            name="o2gear0",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Dissolved Oxygen (mg/l) at Gear [start]",
            ),
        ),
        migrations.AddField(
            model_name="fn121limno",
            name="o2gear1",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Dissolved Oxygen (mg/l) at Gear [end]",
            ),
        ),
        migrations.AddField(
            model_name="fn125tag",
            name="tag_checked",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Has this tag been checked again",
            ),
        ),
    ]
