# Generated by Django 3.2.12 on 2022-09-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0045_popuplate_subspace_from_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn121',
            name='subspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='fn_portal.fn026subspace'),
        ),
    ]
