# Generated by Django 3.2.12 on 2022-09-21 09:59

from django.db import migrations


def populate_fn121_subspace_id(apps, schema_editor):
    """Subspace id is currently empty in the FN121 table - but all of
    the FN026Subspace values are populted. Build a cache of subspace
    id's using their slug as the key and use it to populate the
    subspace_id field in FN121.

    """

    FN026Subspace = apps.get_model("fn_portal", "FN026Subspace")
    FN121 = apps.get_model("fn_portal", "FN121")

    subspace_cache = {
        x[0]: x[1] for x in FN026Subspace.objects.values_list("slug", "id")
    }

    for sample in (
        FN121.objects.prefetch_related("project").select_related("space").all()
    ):
        subspace_slug = "{}-{}-{}".format(
            sample.project.prj_cd, sample.space.space, sample.space.space
        )
        sample.subspace_id = subspace_cache.get(subspace_slug.lower())
        sample.space_id = None
        sample.save()


def unpopulate_fn121_subspace_id(apps, schema_editor):
    """To reverse our operation, we need to get the space id from
    each subspace, and it to populate the space_id field in the FN121
    table.

    """
    FN026Subspace = apps.get_model("fn_portal", "FN026Subspace")
    FN121 = apps.get_model("fn_portal", "FN121")

    subspace_cache = {
        x[0]: x[1] for x in FN026Subspace.objects.values_list("slug", "space_id")
    }

    for sample in (
        FN121.objects.prefetch_related("project").select_related("space").all()
    ):
        sample.space_id = subspace_cache.get(sample.subspace.slug)
        sample.subspace_id = None
        sample.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fn_portal", "0046_add_subspace_fk_to_fn121"),
    ]

    operations = [
        migrations.RunPython(populate_fn121_subspace_id, unpopulate_fn121_subspace_id)
    ]
