# Generated by Django 3.2.12 on 2022-10-14 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0047_template4_tables_and_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fn122',
            old_name='grdep',
            new_name='grdep0',
        ),
        migrations.AddField(
            model_name='fn122',
            name='efftm0',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Effort Start Date'),
        ),
        migrations.AddField(
            model_name='fn122',
            name='efftm1',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Effort End Time'),
        ),
        migrations.AddField(
            model_name='fn122',
            name='grdep1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='efftm0',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Sampling Start Date'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='efftm1',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Sampling End Time'),
        ),
        migrations.AlterField(
            model_name='fn121limno',
            name='o2bot0',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Bottom Dissolved Oxygen (mg/l) [start]'),
        ),
        migrations.AlterField(
            model_name='fn121limno',
            name='o2bot1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Bottom Dissolved Oxygen (mg/l)  [end]'),
        ),
        migrations.AlterField(
            model_name='fn121limno',
            name='o2gear0',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Dissolved Oxygen (mg/l) at Gear [start]'),
        ),
        migrations.AlterField(
            model_name='fn121limno',
            name='o2gear1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Dissolved Oxygen (mg/l) at Gear [end]'),
        ),
        migrations.AlterField(
            model_name='fn121limno',
            name='o2surf0',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Surface Dissolved Oxygen (mg/l)  [start]'),
        ),
        migrations.AlterField(
            model_name='fn121limno',
            name='o2surf1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Surface Dissolved Oxygen (mg/l) [end]'),
        ),
        migrations.AlterField(
            model_name='fn121trawl',
            name='vessel_direction',
            field=models.IntegerField(blank=True, choices=[(0, 'Variable'), (1, 'Northeast'), (2, 'East'), (3, 'Southeast'), (4, 'South'), (5, 'Southwest'), (6, 'West'), (7, 'Northwest'), (8, 'North'), (9, 'Not Definable')], null=True, verbose_name='The direction the vessel was traveling during the sample'),
        ),
        migrations.AlterField(
            model_name='fn121trawl',
            name='vessel_speed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='The speed of the research vessel (knots) during the sample.'),
        ),
        migrations.AlterField(
            model_name='fn121weather',
            name='cloud_pc0',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cloud cover, expressed as a percent at the time when sampling starts.'),
        ),
        migrations.AlterField(
            model_name='fn121weather',
            name='cloud_pc1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cloud cover, expressed as a percent at the time when sampling ends.'),
        ),
        migrations.AlterField(
            model_name='fn121weather',
            name='waveht0',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Wave height measured in meters (m) at the time when sampling starts.'),
        ),
        migrations.AlterField(
            model_name='fn121weather',
            name='waveht1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Wave height measured in meters (m) at the time when sampling ends.'),
        ),
        migrations.AlterField(
            model_name='fn121weather',
            name='wind_direction0',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Wind wind direction in degrees at the time when sampling starts.'),
        ),
        migrations.AlterField(
            model_name='fn121weather',
            name='wind_direction1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Wind wind direction in degrees at the time when sampling ends.'),
        ),
        migrations.AlterField(
            model_name='fn122transect',
            name='dd_lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(41.7), django.core.validators.MaxValueValidator(49.1)], verbose_name='Latitude (dd)'),
        ),
        migrations.AlterField(
            model_name='fn122transect',
            name='dd_lon',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-89.6), django.core.validators.MaxValueValidator(-76.4)], verbose_name='Longitude (dd)'),
        ),
        migrations.AlterField(
            model_name='fn122transect',
            name='sidep',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Site Depth (m)'),
        ),
        migrations.AlterField(
            model_name='fn122transect',
            name='track_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fn123nonfish',
            name='catcnt',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Catch (numbers, including both dead and alive)'),
        ),
        migrations.AlterField(
            model_name='fn123nonfish',
            name='mortcnt',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of dead individuals.'),
        ),
    ]
