# Generated by Django 3.2.12 on 2022-09-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0047_populate_subspace_fk_in_fn121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn121',
            name='space',
        ),
    ]
