# Generated by Django 3.2.12 on 2022-10-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0048_add_0_1_fields_to_fn122'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn012',
            name='agest',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fn012protocol',
            name='agest',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
