# Generated by Django 3.2.12 on 2022-10-14 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0049_add_fn012_agest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn026',
            name='space_wt',
            field=models.FloatField(blank=True, help_text='A weighting factor assigned to a SPACE', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='fn026subspace',
            name='subspace_wt',
            field=models.FloatField(blank=True, help_text='A weighting factor assigned to a SUBSPACE', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
