# Generated by Django 3.2.12 on 2022-10-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_add_vessel_lookup'),
        ('fn_portal', '0050_add_space_wt_and_subspace_wt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn121trawl',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trawl_samples', to='common.vessel'),
        ),
    ]
