# Generated by Django 3.2.12 on 2022-10-18 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0052_fn125_stom_flag_to_choice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn121weather',
            name='waveht0',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3.5)], verbose_name='Wave height measured in meters (m) at the time when sampling starts.'),
        ),
        migrations.AlterField(
            model_name='fn121weather',
            name='waveht1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3.5)], verbose_name='Wave height measured in meters (m) at the time when sampling ends.'),
        ),
        migrations.AlterField(
            model_name='fn122transect',
            name='dd_lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(41.7), django.core.validators.MaxValueValidator(49.2)], verbose_name='Latitude (dd)'),
        ),
        migrations.AlterField(
            model_name='fn122transect',
            name='sidep',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='Site Depth (m)'),
        ),
    ]
