# Generated by Django 3.2.12 on 2022-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0053_adjusted_new_table_field_contstraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn125',
            name='eviswt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
