# Generated by Django 3.2.12 on 2022-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0054_added_fn125_eviswt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn124',
            name='comment4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fn125',
            name='gonwt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fn127',
            name='age_fail',
            field=models.CharField(blank=True, choices=[('91', 'No structure*'), ('92', 'Regenerated Scale / Crystalized Otolith'), ('93', 'Poorly Prepared Structure (poor rolled slide, cracked, sliced etc.)'), ('94', 'Mixed structures / unreliable contaminated sample'), ('95', 'Poor structure / unable to determine reliable age')], max_length=2, null=True, verbose_name='reason for aging attemp failure'),
        ),
        migrations.AddField(
            model_name='fn127',
            name='agelake',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fish Lake Age (yr)'),
        ),
        migrations.AddField(
            model_name='fn127',
            name='agestrm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fish Stream Age (yr)'),
        ),
        migrations.AddField(
            model_name='fn127',
            name='spawnchkcnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='The number of observed spawning checks'),
        ),
    ]
