# Generated by Django 3.2.12 on 2022-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn_portal', '0058_rename_fn122_transects_to_gps_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn125',
            name='age_flag',
        ),
        migrations.RemoveField(
            model_name='fn125',
            name='lam_flag',
        ),
        migrations.RemoveField(
            model_name='fn125',
            name='tag_flag',
        ),
        migrations.AddField(
            model_name='fn125',
            name='stom_contents_wt',
            field=models.FloatField(blank=True, null=True, verbose_name='Stomach contents weight (g)'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='agest',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Age Structures Sampled'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='clipa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Clips applied'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='clipc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Clips on capture'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='eviswt',
            field=models.FloatField(blank=True, null=True, verbose_name='Eviscerated Weight(g)'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='fate',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Fish Fate Code'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='fish',
            field=models.CharField(max_length=6, verbose_name='Fish Id'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='flen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fork Length(mm)'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='girth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Girth (mm)'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='gon',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True, verbose_name='Gonad Condition'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='gonwt',
            field=models.FloatField(blank=True, null=True, verbose_name='Gonad Weigth (g)'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='mat',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='Maturity'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='noda',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nodules applied'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='nodc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nodules present on caputure'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='rwt',
            field=models.FloatField(blank=True, null=True, verbose_name='Round Weight (g)'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='sex',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='A code identifying the sex of a fish.'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='tissue',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tissues Sampled'),
        ),
        migrations.AlterField(
            model_name='fn125',
            name='tlen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Length(mm)'),
        ),
    ]
