--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

--
-- Data for Name: fn_portal_gear; Type: TABLE DATA; Schema: public; Owner: cottrillad
--

INSERT INTO fn_portal_gear VALUES (212, 7, 'Unknown Gill Net!', 'GL11', NULL, NULL, 'This gear was used in 8 net sets in a single project (LHA_IS94_013).  No information is currently available on this gear.', '<p>This gear was used in 8 net sets in a single project (LHA_IS94_013).  No information is currently available on this gear.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (213, 9, 'Unknown Gill Net! / 50M Panel Of 51 Mm Monfilament', 'GL12', 1, 50, 'This gear has been used in two different projects. In LHA_IA02_140 it was used for a single net set consisting of one 50m panel of 51mm mesh.  It was also used in LHA_IS94_013.  No information is available on the gear in that project.', '<p>This gear has been used in two different projects. In LHA_IA02_140 it was used for a single net set consisting of one 50m panel of 51mm mesh.  It was also used in LHA_IS94_013.  No information is available on the gear in that project.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (214, 9, 'Unknown Gill Net! / 50M Panel Of 64 Mm Monfilament', 'GL13', 1, 50, 'This gear has been used in 7 different projects. Between 2002 and 2009, it was used to identify a net consiting of a single 50m panel of 64mm mesh.  It was also used in LHA_IS94_013.  No information is available on the gear in that project.', '<p>This gear has been used in 7 different projects. Between 2002 and 2009, it was used to identify a net consiting of a single 50m panel of 64mm mesh.  It was also used in LHA_IS94_013.  No information is available on the gear in that project.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (215, 7, 'Unknown Gill Net!', 'GL14', NULL, NULL, 'This gear was used in 2 projects (LHA_IS93_013, LHA_94_013).  This gear code appears to have been used to identify nets with 051 mm mesh.  No indication on gear length  or material.', '<p>This gear was used in 2 projects (LHA_IS93_013, LHA_94_013).  This gear code appears to have been used to identify nets with 051 mm mesh.  No indication on gear length  or material.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (217, 7, 'Unknown Gill Net!', 'GL16', NULL, NULL, 'This gear was used in 1 project (LHA_94_013).  This gear code appears to have been used to identify nets with  38mm mesh.  No indication on gear length  or material.', '<p>This gear was used in 1 project (LHA_94_013).  This gear code appears to have been used to identify nets with  38mm mesh.  No indication on gear length  or material.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (218, 7, 'Unknown Gill Net!', 'GL17', NULL, NULL, 'This gear was used in 1 project (LHA_94_013).  This gear code appears to have been used to identify nets with  51mm mesh.  No indication on gear length  or material.', '<p>This gear was used in 1 project (LHA_94_013).  This gear code appears to have been used to identify nets with  51mm mesh.  No indication on gear length  or material.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (211, 9, 'Lhfau Poly Monofilament Index Gillnet', 'GL10', 8, 375, 'This is the standard offshore index monofilament gill net gear that was used from 1993-2005 and consisted of 8 meshes ranging from 38-127mm.  Meshes were arranged sequentially.

Note there are some GL10 efforts with an additional 25mm mesh - these are a different gear and should be recoded as such.

', '<p>This is the standard offshore index monofilament gill net gear that was used from 1993-2005 and consisted of 8 meshes ranging from 38-127mm.  Meshes were arranged sequentially.</p>
<p>Note there are some GL10 efforts with an additional 25mm mesh - these are a different gear and should be recoded as such.</p>', true, false, NULL);
INSERT INTO fn_portal_gear VALUES (198, 5, 'Fy01 - Fyke Net', 'FY01', 1, NULL, 'Fyke Nets used in small fish program, 2003-2008.  Not clear how this gear is different from FY02 or FY03.', '<p>Fyke Nets used in small fish program, 2003-2008.  Not clear how this gear is different from FY02 or FY03.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (202, 6, 'Gee/Minnow Trap', 'GEE', 1, NULL, 'Standard minnow traps used in the small fish assessment program between 2003 and 2008.  These does not appear to be a distinction between black or chrome traps, or if the traps were baited, and if so, with what.', '<p>Standard minnow traps used in the small fish assessment program between 2003 and 2008.  These does not appear to be a distinction between black or chrome traps, or if the traps were baited, and if so, with what.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (199, 5, 'Fy02 - Fyke Net', 'FY02', 1, NULL, 'Fyke Nets used in small fish program, 2003-2008.  Not clear how this gear is different from FY01 or FY03.', '<p>Fyke Nets used in small fish program, 2003-2008.  Not clear how this gear is different from FY01 or FY03.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (195, 2, 'Bottle Trap', 'BOT', 1, NULL, 'Bottle traps deployed in the small fish assessment program to target hemimysis.', '<p>Bottle traps deployed in the small fish assessment program to target hemimysis.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (200, 5, 'Fy03 - Fyke Net', 'FY03', 1, NULL, 'Fyke Nets used in small fish program, 2008-2015.  Not clear how this gear is different from FY01 or FY02.', '<p>Fyke Nets used in small fish program, 2008-2015.  Not clear how this gear is different from FY01 or FY02.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (197, 4, 'Electrofishing', 'EL', NULL, NULL, 'Electro fishing', '<p>Electro fishing</p>', false, false, 7);
INSERT INTO fn_portal_gear VALUES (219, 9, 'Lhfau Poly Monofilament Index Gillnet - With 25Mm Panel', 'GL18', 9, 390, 'This is the standard offshore index monofilament gill net gear with an additional 15m panel of 25mm mesh.   

This gear code was also used in the 1995 Iroquios Bay FLIN where it was used to identify the catch in the 76mm net.  No gear length or material is reported in this project.', '<p>This is the standard offshore index monofilament gill net gear with an additional 15m panel of 25mm mesh.   </p>
<p>This gear code was also used in the 1995 Iroquios Bay FLIN where it was used to identify the catch in the 76mm net.  No gear length or material is reported in this project.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (220, 9, 'Offshore Index Chub Net/Unknown Net', 'GL19', 4, 350, 'This gear was used in Tobermory/Lion''s Head chub index in 2002-2004 and again in 2012.  It is a mono-filament version of GL02 and consisted of a 50m panel of 38, followed by 100 m panels of 51, 64 and 76 mm mesh.  This gear code was also used in LHA_IS95_013 although no catch was ever reported in the samples that used this gear and no description of the gear is available.', '<p>This gear was used in Tobermory/Lion''s Head chub index in 2002-2004 and again in 2012.  It is a mono-filament version of GL02 and consisted of a 50m panel of 38, followed by 100 m panels of 51, 64 and 76 mm mesh.  This gear code was also used in LHA_IS95_013 although no catch was ever reported in the samples that used this gear and no description of the gear is available.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (206, 8, 'Offshore Chub Nets - With 65Mm', 'GL03', 5, 410, '38-76 mm panels from GL01 Multifilament gillnets and appears to include both 64 and 65mm meshes?.  Used in tobermory/lion''s head chub surveys beteen 1991 and 1993.', '<p>38-76 mm panels from GL01 Multifilament gillnets and appears to include both 64 and 65mm meshes?.  Used in tobermory/lion''s head chub surveys beteen 1991 and 1993.</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (207, 8, 'North Channel Spake Nets', 'GL04', 13, 1417, 'Gear used bewteen 1985 and 1992 in the North Channel Darch/Heywood Island back cross index programs.', '<p>Gear used bewteen 1985 and 1992 in the North Channel Darch/Heywood Island back cross index programs.</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (208, 8, 'Owen Sound Depth-Temperature Index', 'GL06', 3, 273, 'This gear was used in a single project in 1991.  Consisted of of 91 m panels 51, 76, and 102 mm meshes from multifilament index nets.', '<p>This gear was used in a single project in 1991.  Consisted of of 91 m panels 51, 76, and 102 mm meshes from multifilament index nets.</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (210, 8, 'North Channel Co-Op Index Gill Net - Short', 'GL09', 3, 138, 'This gear was used in north channel cooperative index fishing projects between 1993 and 1996  and consisted of 46 m panels of 51, 64, and 76 mm meshes (presumably) from multifilament index nets.', '<p>This gear was used in north channel cooperative index fishing projects between 1993 and 1996  and consisted of 46 m panels of 51, 64, and 76 mm meshes (presumably) from multifilament index nets.</p>', false, true, 3);
INSERT INTO fn_portal_gear VALUES (223, 9, 'Lhfau Poly Monofilament Index Gillnet - Large Mesh Lake Trout Spawning', 'GL22', 5, 250, 'This gear was introduced in 2008 in support of the Lake Huron Lake Trout rehabiliation plan.  It consists of 50 m panels of the larges mesh sizes from offshore index gear (GL21) and is intended to collect CPUE metrics of Lake Trout spawner abundance that are consistent eith the rehabiliation plan, lake trout surveys in other juristictions and the UGLMU offshore index program.', '<p>This gear was introduced in 2008 in support of the Lake Huron Lake Trout rehabiliation plan.  It consists of 50 m panels of the larges mesh sizes from offshore index gear (GL21) and is intended to collect CPUE metrics of Lake Trout spawner abundance that are consistent eith the rehabiliation plan, lake trout surveys in other juristictions and the UGLMU offshore index program.</p>', true, false, NULL);
INSERT INTO fn_portal_gear VALUES (225, 9, 'Whitefish Spawning Survey - Short', 'GL26', 1, 50, 'This gear was used in 2 projects (LHA_IS04_240 and LHA_IS05_240).  This gear code was used to designate nets that consisted of one 50m panel of 114 mm mesh.', '<p>This gear was used in 2 projects (LHA_IS04_240 and LHA_IS05_240).  This gear code was used to designate nets that consisted of one 50m panel of 114 mm mesh.</p>', true, false, 1);
INSERT INTO fn_portal_gear VALUES (226, 9, 'Whitefish Spawning Survey - Long', 'GL27', 1, 100, 'This gear was used in 1 project (LHA_IS04_240).  This gear code was used to designate nets that consisted of two 50m panels of 114 mm mesh.  Effort was used to distinguish between catches in the nearshore and offshore panels.', '<p>This gear was used in 1 project (LHA_IS04_240).  This gear code was used to designate nets that consisted of two 50m panels of 114 mm mesh.  Effort was used to distinguish between catches in the nearshore and offshore panels.</p>', true, false, 1);
INSERT INTO fn_portal_gear VALUES (227, 9, 'Lhfau Poly Monofilament Index Gillnet - With 32Mm Panel', 'GL32', 9, 390, 'This is the standard offshore index monofilament gill net gear with an additional 15m panel of 32mm mesh.   This gear was used in the offshore index between 2002 and 2013 before it was phased out in favour of GL21 (included 2 larger meshes and randomize panel order).  NOTE: There are several projects with samples that use this gear that should probably be GL21 (check via effcnt and sum of effdst).', '<p>This is the standard offshore index monofilament gill net gear with an additional 15m panel of 32mm mesh.   This gear was used in the offshore index between 2002 and 2013 before it was phased out in favour of GL21 (included 2 larger meshes and randomize panel order).  NOTE: There are several projects with samples that use this gear that should probably be GL21 (check via effcnt and sum of effdst).</p>', true, false, NULL);
INSERT INTO fn_portal_gear VALUES (228, 10, '6 - 50 Ft Panels Of 38Mm Mono Net ', 'GL38', 1, 91.400000000000006, 'This is a 38mm FLIN/SLIN net.  Effort may have been used to identify the inshore and offshore components of the net.', '<p>This is a 38mm FLIN/SLIN net.  Effort may have been used to identify the inshore and offshore components of the net.</p>', true, false, NULL);
INSERT INTO fn_portal_gear VALUES (224, 7, 'Unknown Gill Net!', 'GL25', NULL, NULL, 'This gear was used in 1 project (LHA_IS96_013).  This was the only gear used in this project, however, there is no indication on gear length, material, or mesh size.


***After meeting (03/27/2017 with C. Davis, S. Currie, A. Cottril, and A.Conway) to discuss gear codes. GL15, GL20, and GL25 will be the GR used for FLINs and SLINs moving forward. This means projects using this "GL25" will need to be identified and assigned a new code if they do not conform to the configuration listed below:

A GL25 is 3 panels of 64mm mesh. Length: 45.7m

From SLIN manual:

"The standard gear is 3 mesh sizes of monofilament gillnet, made in Finland according to the specifications that were established by the B.C. Ministry of the Environmnet. The configuration is a 91.4m (300ft) gillnet gang, comprised of six 15.2m (50ft) X 2.4 (8ft) panels tied together with the brail loops. All six panels per gang are of the same mesh size, either 38mm (1.5 in), 51mm (2.5 in), or 65mm (2.5 in) stretched mesh. The nets, referred to as "monofilament research gillnets" are available from two Canadian distributors. "

-AJC', '<p>This gear was used in 1 project (LHA_IS96_013).  This was the only gear used in this project, however, there is no indication on gear length, material, or mesh size.</p>
<p>***After meeting (03/27/2017 with C. Davis, S. Currie, A. Cottril, and A.Conway) to discuss gear codes. GL15, GL20, and GL25 will be the GR used for FLINs and SLINs moving forward. This means projects using this "GL25" will need to be identified and assigned a new code if they do not conform to the configuration listed below:</p>
<p>A GL25 is 3 panels of 64mm mesh. Length: 45.7m</p>
<p>From SLIN manual:</p>
<p>"The standard gear is 3 mesh sizes of monofilament gillnet, made in Finland according to the specifications that were established by the B.C. Ministry of the Environmnet. The configuration is a 91.4m (300ft) gillnet gang, comprised of six 15.2m (50ft) X 2.4 (8ft) panels tied together with the brail loops. All six panels per gang are of the same mesh size, either 38mm (1.5 in), 51mm (2.5 in), or 65mm (2.5 in) stretched mesh. The nets, referred to as "monofilament research gillnets" are available from two Canadian distributors. "</p>
<p>-AJC</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (231, 7, 'Gill Net Lake Survey Net ', 'GL60', NULL, NULL, 'This gear was used in a single project (LHA_IA98_231).  No gear description, mesh size, length or material is available.  Large catches of spotfin shiner suggest that it was probably a small mesh net.', '<p>This gear was used in a single project (LHA_IA98_231).  No gear description, mesh size, length or material is available.  Large catches of spotfin shiner suggest that it was probably a small mesh net.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (229, 11, 'Lhfau Poly Monofilament Fwin Gillnet', 'GL50', 8, 60.799999999999997, 'This is a standard FWIN net consisting of 7.6 m panels of graded mesh from 25 mm to 152 mm.  ', '<p>This is a standard FWIN net consisting of 7.6 m panels of graded mesh from 25 mm to 152 mm.  </p>', true, false, NULL);
INSERT INTO fn_portal_gear VALUES (233, 10, '6 - 50 Ft Panels Of 64Mm Mono Net ', 'GL64', 1, 91.400000000000006, 'This is a 64mm FLIN/SLIN net.  Effort may have been used to identify the inshore and offshore components of the net.', '<p>This is a 64mm FLIN/SLIN net.  Effort may have been used to identify the inshore and offshore components of the net.</p>', true, false, NULL);
INSERT INTO fn_portal_gear VALUES (235, 12, 'Undocumented Hoop Net', 'HP01', NULL, NULL, 'This gear has been used in 13 SMIN projects starting in 2006.  There is currently no gear description or details available.  It is not clear if, or how, this gear differs from HP.', '<p>This gear has been used in 13 SMIN projects starting in 2006.  There is currently no gear description or details available.  It is not clear if, or how, this gear differs from HP.</p>', false, false, 7);
INSERT INTO fn_portal_gear VALUES (234, 12, 'Undocumented Hoop Net', 'HP', NULL, NULL, 'This gear has been used in 13 SMIN projects starting in 2006.  There is currently no gear description or details available.  It is not clear if, or how, this gear differs from HP01.', '<p>This gear has been used in 13 SMIN projects starting in 2006.  There is currently no gear description or details available.  It is not clear if, or how, this gear differs from HP01.</p>', false, false, 7);
INSERT INTO fn_portal_gear VALUES (240, 17, 'Smallfish Index Net - Short?', 'SIN1', 7, 10.640000000000001, 'This gear has been used in the small fish survey since 2007.  It consists of 7 different meshes ranging from 13-51mm. Individual panels are 1.52m long.  This gear is exactly the same as SIN2, but only half as high (0.9m).', '<p>This gear has been used in the small fish survey since 2007.  It consists of 7 different meshes ranging from 13-51mm. Individual panels are 1.52m long.  This gear is exactly the same as SIN2, but only half as high (0.9m).</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (236, 13, 'North American Standard Index Gillnet', 'NA1', 8, 49.600000000000001, 'This gear is the large-mesh gill net used in the Broad Scale Monitoring (BSM) program.  It consists of 8 different meshes (2x3.1m panels of 38mm to 127mm monofilament mesh).  This gear was first used on Lake Huron in 2014.', '<p>This gear is the large-mesh gill net used in the Broad Scale Monitoring (BSM) program.  It consists of 8 different meshes (2x3.1m panels of 38mm to 127mm monofilament mesh).  This gear was first used on Lake Huron in 2014.</p>', false, false, 4);
INSERT INTO fn_portal_gear VALUES (238, 15, 'Ontario Small Fish Gillnet', 'ON2', 5, 25, 'This gear is the small-mesh gill net used in the Broad Scale Monitoring (BSM) program.  It consists of 8 different meshes (2x2.5m panels of 13mm to 38mm monofilament mesh).  This gear was first used on Lake Huron in 2014.', '<p>This gear is the small-mesh gill net used in the Broad Scale Monitoring (BSM) program.  It consists of 8 different meshes (2x2.5m panels of 13mm to 38mm monofilament mesh).  This gear was first used on Lake Huron in 2014.</p>', false, false, 5);
INSERT INTO fn_portal_gear VALUES (241, 18, 'Smallfish Index Net - Tall?', 'SIN2', 7, 10.640000000000001, 'This gear was only used in the small fish survey program in 2007.  It consists of 7 different meshes ranging from 13-51mm. Individual panels are 1.52m long.  This gear is exactly the same as SIN1, but twice as high (1.8m).', '<p>This gear was only used in the small fish survey program in 2007.  It consists of 7 different meshes ranging from 13-51mm. Individual panels are 1.52m long.  This gear is exactly the same as SIN1, but twice as high (1.8m).</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (239, 16, 'Undocumented Seine Net', 'SE', NULL, NULL, 'This gear code was used to designate samples collected with a beach seine in the small fish project between 2003 and 2005.  No description of the gear details (material, length ect) is currently available.', '<p>This gear code was used to designate samples collected with a beach seine in the small fish project between 2003 and 2005.  No description of the gear details (material, length ect) is currently available.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (232, 7, 'Undocumented Gill Net', 'GL61', NULL, NULL, 'This gear was used in a single project (LHA_IA98_231).  No gear description, mesh size, length or material is available.  The catch was limited to walleye, northern pike and yellow perch suggest that this gear was probably moderately sized (>=51mm).', '<p>This gear was used in a single project (LHA_IA98_231).  No gear description, mesh size, length or material is available.  The catch was limited to walleye, northern pike and yellow perch suggest that this gear was probably moderately sized (&gt;=51mm).</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (230, 10, '6 - 50 Ft Panels Of 51Mm Mono Net ', 'GL51', 1, 91.400000000000006, 'This is a 51mm FLIN/SLIN net.  Effort may have been used to identify the inshore and offshore components of the net.

', '<p>This is a 51mm FLIN/SLIN net.  Effort may have been used to identify the inshore and offshore components of the net.</p>', true, true, NULL);
INSERT INTO fn_portal_gear VALUES (243, 1, '6'' Trap Net', 'TP00', NULL, NULL, 'This gear code was only used in the Key River ESTN (LHA_IA98_232).  Project documentation indicates that it was a 6'' Standard Trap net.', '<p>This gear code was only used in the Key River ESTN (LHA_IA98_232).  Project documentation indicates that it was a 6'' Standard Trap net.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (244, 1, '8'' Trapnet', 'TP01', NULL, NULL, 'This gear code appears twice in FN013 table (LHA_IA96_113 and LHA_IS00_014) - both projects indicate that it was used to identify 8'' trap net.  Additionally, it appears in the FN121 table for Gravelly Bay Lake Trout Spawning assessment from 1996-2010.  Available documentation for these projects indicate that 8'' trap nets were used exclusively for this project.', '<p>This gear code appears twice in FN013 table (LHA_IA96_113 and LHA_IS00_014) - both projects indicate that it was used to identify 8'' trap net.  Additionally, it appears in the FN121 table for Gravelly Bay Lake Trout Spawning assessment from 1996-2010.  Available documentation for these projects indicate that 8'' trap nets were used exclusively for this project.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (246, 1, 'Undocumented Trap Net', 'TP03', NULL, NULL, 'This code has been used in 76 different projects starting in 1994.  The available FN013 records indicate that this code was used to identify both 6'' and 8'' trapnets.', '<p>This code has been used in 76 different projects starting in 1994.  The available FN013 records indicate that this code was used to identify both 6'' and 8'' trapnets.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (247, 1, 'Undocumented Trap Net', 'TP04', NULL, NULL, 'This code has been used in 31 different projects starting in 1992.  The available FN013 records indicate that this code was used to identify both 6'' and 8'' trapnets.', '<p>This code has been used in 31 different projects starting in 1992.  The available FN013 records indicate that this code was used to identify both 6'' and 8'' trapnets.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (248, 1, '5'' Trapnet', 'TP05', NULL, NULL, 'This gear was used in two projects: Shebeshekong River NSCIN (LHA_IA97_025) and Severn Sound SMIN(LHA_IA98_250).  Both projects indicate that it was a 5'' trapnet, although the Shebeshekong project also indicates that it was ''small-mesh''. It''s not clear if that description applies to the Severn Sound Project or not.', '<p>This gear was used in two projects: Shebeshekong River NSCIN (LHA_IA97_025) and Severn Sound SMIN(LHA_IA98_250).  Both projects indicate that it was a 5'' trapnet, although the Shebeshekong project also indicates that it was ''small-mesh''. It''s not clear if that description applies to the Severn Sound Project or not.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (249, 1, '6'' Trapnet', 'TP06', NULL, NULL, 'This gear code appears in the FN013 table for 3 different near shore projects (LHA_IA98_250,LHA_IA99_251 andLHA_IA00_251) but does not appear in the FN121 table for those projects.  The FN121 table for the *251 projects use TP03 exclusively and the project documentation indicates that 6'' trap nets were used.   The FN013 table indicates that this code corresponds to 6'' trapnets for these projects.  The gear field in the FN121 table for *250 project has been trucated and will be updated from the FN Archive.  5,6, and 8'' trapnets appear to have been used in the *250 project. This gear code also appears in two parry sound lake trout spawning surveys/egg collection programs in 2008 and 2009. Documentation associted with the 2008 project indicate that 6'' trap nets were used.  The 2009 project is completely undocumented.', '<p>This gear code appears in the FN013 table for 3 different near shore projects (LHA_IA98_250,LHA_IA99_251 andLHA_IA00_251) but does not appear in the FN121 table for those projects.  The FN121 table for the <em>251 projects use TP03 exclusively and the project documentation indicates that 6'' trap nets were used.   The FN013 table indicates that this code corresponds to 6'' trapnets for these projects.  The gear field in the FN121 table for </em>250 project has been trucated and will be updated from the FN Archive.  5,6, and 8'' trapnets appear to have been used in the *250 project. This gear code also appears in two parry sound lake trout spawning surveys/egg collection programs in 2008 and 2009. Documentation associted with the 2008 project indicate that 6'' trap nets were used.  The 2009 project is completely undocumented.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (250, 1, '8'' Trapnet', 'TP08', NULL, NULL, 'This gear code appears in the FN121 table for a number of Lake Trout Spawning surveys run in South Bay and Parry sound since 2012.  The Parry sound lake trout projects are not adequated documented.  The gear code also appears in the FN013 table associated with Severn Sound SMIN(LHA_IA98_250) where it is described as a 8'' trapnet.  The gear code is not currenly in the FN121 table for this project but was used in the FN archive.  Update the master.', '<p>This gear code appears in the FN121 table for a number of Lake Trout Spawning surveys run in South Bay and Parry sound since 2012.  The Parry sound lake trout projects are not adequated documented.  The gear code also appears in the FN013 table associated with Severn Sound SMIN(LHA_IA98_250) where it is described as a 8'' trapnet.  The gear code is not currenly in the FN121 table for this project but was used in the FN archive.  Update the master.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (251, 1, '6'' Trapnet', 'TP3', NULL, NULL, 'This gear was used in a single project - Shebeshekong River Spawning Survey LHA_IA94_015. It was reported as a 6'' Trapnet.', '<p>This gear was used in a single project - Shebeshekong River Spawning Survey LHA_IA94_015. It was reported as a 6'' Trapnet.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (252, 1, '6'' Trapnet', 'TP31', NULL, NULL, 'This gear was used in 4 NSCIN projects on 1996 andf 1997. All projects report this code as a 6'' Trapnet.', '<p>This gear was used in 4 NSCIN projects on 1996 andf 1997. All projects report this code as a 6'' Trapnet.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (253, 1, '6'' Trapnet', 'TP32', NULL, NULL, 'This gear was used in 4 NSCIN projects on 1996 andf 1997. All projects report this code as a 6'' Trapnet.', '<p>This gear was used in 4 NSCIN projects on 1996 andf 1997. All projects report this code as a 6'' Trapnet.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (245, 1, 'Undocumented Trap Net', 'TP02', NULL, NULL, 'This code was used in 10 projects between 1996 and 1998.  Some projects define it as a 6'' trapnet, others define it as an 8'' trapnet.  In the LHA_IS97_014, it appears to have been used to distinguish between two different trap nets (sites).', '<p>This code was used in 10 projects between 1996 and 1998.  Some projects define it as a 6'' trapnet, others define it as an 8'' trapnet.  In the LHA_IS97_014, it appears to have been used to distinguish between two different trap nets (sites).</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (254, 1, '6'' Trapnet', 'TP33', NULL, NULL, 'This gear was used in 4 NSCIN projects on 1996 andf 1997. All projects report this code as a 6'' Trapnet.', '<p>This gear was used in 4 NSCIN projects on 1996 andf 1997. All projects report this code as a 6'' Trapnet.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (255, 1, '6'' Trapnet', 'TP34', NULL, NULL, 'This gear was used in 2 NSCIN projects (Moon River NSCIN - LHA_IA96_002 and MacGregor Bay NSCIN - LHA_IA97_115).  Both projects report this code as a 6'' Trapnet.', '<p>This gear was used in 2 NSCIN projects (Moon River NSCIN - LHA_IA96_002 and MacGregor Bay NSCIN - LHA_IA97_115).  Both projects report this code as a 6'' Trapnet.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (256, 1, 'Unknown Trapnet!', 'TP99', NULL, NULL, 'This gear was used in a single project (French River Delta NSCIN - LHA_IA96_021).  Three other gear codes where used in this project - all of them where reported to be 6'' trapnets.   No gear description or details are currently available.', '<p>This gear was used in a single project (French River Delta NSCIN - LHA_IA96_021).  Three other gear codes where used in this project - all of them where reported to be 6'' trapnets.   No gear description or details are currently available.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (259, 19, 'Bottom Trawl', 'TW01', NULL, NULL, 'This gear was used in bottom trawl programs off of Goderich between 1982 and 1990.  The surveys were conducted by the USFWS.  No gear description or details are currently available.', '<p>This gear was used in bottom trawl programs off of Goderich between 1982 and 1990.  The surveys were conducted by the USFWS.  No gear description or details are currently available.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (205, 8, 'Offshore Chub Nets', 'GL02', 4, 319, '38-76 mm panels from GL01 Multifilament gillnets (on chub surveys between 1990 and 1993).  The 1990 nets appear to have an extra panel and could be GL03s.', '<p>38-76 mm panels from GL01 Multifilament gillnets (on chub surveys between 1990 and 1993).  The 1990 nets appear to have an extra panel and could be GL03s.</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (209, 8, 'North Channel Co-Op Index Gill Net - Long', 'GL08', 3, 273, 'This gear was used in a single project in 1992.  Consisted of 91 m panels of 51, 64, and 76 mm meshes (presumably) from multifilament index nets.  EFFDST of FN122 table needs to be updated according.', '<p>This gear was used in a single project in 1992.  Consisted of 91 m panels of 51, 64, and 76 mm meshes (presumably) from multifilament index nets.  EFFDST of FN122 table needs to be updated according.</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (204, 8, 'Standard Lhfau Nylon Multifilament Index Gillnet ', 'GL01', 8, 683, 'STANDARD LHFAU NYLON MULTIFILAMENT INDEX GILLNET (this gear code was used a lot prior to 1994.  Gear length seems to be hightly variable - Interpret with caution).', '<p>STANDARD LHFAU NYLON MULTIFILAMENT INDEX GILLNET (this gear code was used a lot prior to 1994.  Gear length seems to be hightly variable - Interpret with caution).</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (193, 1, 'Presumed To Be 8'' Trap Net.', '6', 1, NULL, 'Used in a single project (LHR_IA94_107) - lake trout trap netting in Owen Sound.  Presumably this is a 6'' trap net.', '<p>Used in a single project (LHR_IA94_107) - lake trout trap netting in Owen Sound.  Presumably this is a 6'' trap net.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (194, 1, 'Presumed To Be 6'' Trap Net.', '8', 1, NULL, 'Used in a single project (LHR_IA94_107) - lake trout trap netting in Owen Sound.  Presumably this is a 8'' trap net.', '<p>Used in a single project (LHR_IA94_107) - lake trout trap netting in Owen Sound.  Presumably this is a 8'' trap net.</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (242, 1, 'Undocumented Trap Net', 'TP', NULL, NULL, 'This gear code was used sporadically between 1995 and 2010.  Most of the projects are SMINs.  It also appears to have been used in an ESTN Project (LHA_IA01_251) and two lake trout projects (LHR_IA95_107 and LHA_IS10_018).  Documentation associated with the parry sound project inidcate that these were 6'' trap nets.  The Owen Sound and Severn Sound projects appear to be completely undocumented and documentation of the swin projects indicates that nets varied in size from 6'' to 8'' (??).', '<p>This gear code was used sporadically between 1995 and 2010.  Most of the projects are SMINs.  It also appears to have been used in an ESTN Project (LHA_IA01_251) and two lake trout projects (LHR_IA95_107 and LHA_IS10_018).  Documentation associated with the parry sound project inidcate that these were 6'' trap nets.  The Owen Sound and Severn Sound projects appear to be completely undocumented and documentation of the swin projects indicates that nets varied in size from 6'' to 8'' (??).</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (258, 1, 'Commercial Trap Net', 'TPH', NULL, NULL, 'This gear was used in a single project ( Southern Lake Huron Co-Op Index - LHA_IA93_012).  It is likely that this is commerical trap net gear from which walleye were sampled.  No other species were reported.  No gear description or details are currently available.', '<p>This gear was used in a single project ( Southern Lake Huron Co-Op Index - LHA_IA93_012).  It is likely that this is commerical trap net gear from which walleye were sampled.  No other species were reported.  No gear description or details are currently available.</p>', false, true, 3);
INSERT INTO fn_portal_gear VALUES (257, 1, 'Commercial Trap Net', 'TPG', NULL, NULL, 'This gear was used in a single project ( Southern Lake Huron Co-Op Index - LHA_IA93_012).  It is likely that this is commerical trap net gear from which walleye were sampled.  No other species were reported.  No gear description or details are currently available.', '<p>This gear was used in a single project ( Southern Lake Huron Co-Op Index - LHA_IA93_012).  It is likely that this is commerical trap net gear from which walleye were sampled.  No other species were reported.  No gear description or details are currently available.</p>', false, true, 3);
INSERT INTO fn_portal_gear VALUES (201, 5, 'Fy04 - Fyke Net', 'FY04', 1, NULL, 'Fyke Nets used in small fish program, 2008-2015.  Not clear how this gear is different from FY01 or FY02 or FY03.', '<p>Fyke Nets used in small fish program, 2008-2015.  Not clear how this gear is different from FY01 or FY02 or FY03.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (260, 20, 'Windemere Traps', 'WN', NULL, NULL, 'This gear was used in 9 net sets in a single project.  Owen Sound Smallfish Survery (LHA_IA03_700).  No gear description or details are currently available.', '<p>This gear was used in 9 net sets in a single project.  Owen Sound Smallfish Survery (LHA_IA03_700).  No gear description or details are currently available.</p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (237, 14, 'Nordic Index Gill Net', 'NOR', 12, 30, 'This gear was used in the small fish survey between 2003 and 2008.  It was also used in a single project in 2011 to collect contaminant samples.  The normally this gear is well document as part od the Nordic protocol for small fish assessment and includes meshes from 6-55 mm.  CHECK: catches in additional meshes in the 2003 small fish survey suggest that the gear used in that year may have been different that subsquent years and should probably be assigned an alternative gear code (e.g. NOR1).  NOTE: the manual states the mesh sizes are knot-to-knot.  By convention, EFF is the stretch measure of mesh size which may not be the case for fish caught in this gear. ', '<p>This gear was used in the small fish survey between 2003 and 2008.  It was also used in a single project in 2011 to collect contaminant samples.  The normally this gear is well document as part od the Nordic protocol for small fish assessment and includes meshes from 6-55 mm.  CHECK: catches in additional meshes in the 2003 small fish survey suggest that the gear used in that year may have been different that subsquent years and should probably be assigned an alternative gear code (e.g. NOR1).  NOTE: the manual states the mesh sizes are knot-to-knot.  By convention, EFF is the stretch measure of mesh size which may not be the case for fish caught in this gear. </p>', false, false, 2);
INSERT INTO fn_portal_gear VALUES (196, 3, 'Cora Large-Mesh, Lake Trout Assessment Nets', 'CRA', 8, 244, 'Large mesh, multifilament gill nets lent to UGLMU by CORA.  Used in a single project (LHA_IS05_CRA).  

The gear consisted of 8 100'' panels of large mesh multifilament -meshes ranged from 4.5-6".  There were two panel of each size and panels were randomly ordered.  

Note: As there were two panels of each size eff does not correspond to mesh size for this gear.  Catch was reported by panel (eff).
', '<p>Large mesh, multifilament gill nets lent to UGLMU by CORA.  Used in a single project (LHA_IS05_CRA).  </p>
<p>The gear consisted of 8 100'' panels of large mesh multifilament -meshes ranged from 4.5-6".  There were two panel of each size and panels were randomly ordered.  </p>
<p>Note: As there were two panels of each size eff does not correspond to mesh size for this gear.  Catch was reported by panel (eff).</p>', true, true, 1);
INSERT INTO fn_portal_gear VALUES (203, 7, 'Undocumented Gillnet!', 'GL', NULL, NULL, 'Generic gill net - This code is provided for historical data and should not be used in current projects.



This generic code was used to identify Lake Huron Research Offshore Index nets from 1965-1992. The nets in these years have different configurations - this code doesn''t appear to be very useful. -AC', '<p>Generic gill net - This code is provided for historical data and should not be used in current projects.</p>
<p>This generic code was used to identify Lake Huron Research Offshore Index nets from 1965-1992. The nets in these years have different configurations - this code doesn''t appear to be very useful. -AC</p>', false, true, NULL);
INSERT INTO fn_portal_gear VALUES (222, 9, 'Lhfau Poly Monofilament Index Gillnet - With 140 And 153 Mm Panels And Randomize Panel Sequence.', 'GL21', 11, 490, 'This gear was introduced in the offshore index in 2008.  It uses the same panels as GL32 with the addition of 50 m panels of 140 and 153 mm mesh.  Additionally, the order of the panels is randomized to minimize the potenial of leading/set bias.

From a field protocol report from LHR (http://142.143.160.56:8080/projects/projectdetail/lha_ia08_119/):

"One of the three gangs will also include 50 m panels of 5.5” (140 mm) and 6.0” (165 mm) mesh and will have the order of the meshes randomized.  The gear code for this net configuration is GL21 and the total gear length will be 490 m.  The order of all panels in this third net is to be randomized between projects and seasons."

-AC', '<p>This gear was introduced in the offshore index in 2008.  It uses the same panels as GL32 with the addition of 50 m panels of 140 and 153 mm mesh.  Additionally, the order of the panels is randomized to minimize the potenial of leading/set bias.</p>
<p>From a field protocol report from LHR (http://142.143.160.56:8080/projects/projectdetail/lha_ia08_119/):</p>
<p>"One of the three gangs will also include 50 m panels of 5.5” (140 mm) and 6.0” (165 mm) mesh and will have the order of the meshes randomized.  The gear code for this net configuration is GL21 and the total gear length will be 490 m.  The order of all panels in this third net is to be randomized between projects and seasons."</p>
<p>-AC</p>', true, false, NULL);
INSERT INTO fn_portal_gear VALUES (221, 7, 'Unknown Gill Net!', 'GL20', NULL, NULL, 'This gear was used in 1 project (LHA_95_013).  No catch was reported for the samples that used this gear code. There is no indication on gear length  or material.

***After meeting (03/27/2017 with C. Davis, S. Currie, A. Cottril, and A.Conway) to discuss gear codes. GL15, GL20, and GL25 will be the GR used for FLINs and SLINs moving forward. This means projects using this "GL20" will need to be identified and assigned a new code if they do not conform to the configuration listed below:

A GL20 is 3 panels of 51mm mesh. Length: 45.7m


From SLIN manual:

"The standard gear is 3 mesh sizes of monofilament gillnet, made in Finland according to the specifications that were established by the B.C. Ministry of the Environmnet. The configuration is a 91.4m (300ft) gillnet gang, comprised of six 15.2m (50ft) X 2.4 (8ft) panels tied together with the brail loops. All six panels per gang are of the same mesh size, either 38mm (1.5 in), 51mm (2.5 in), or 65mm (2.5 in) stretched mesh. The nets, referred to as "monofilament research gillnets" are available from two Canadian distributors. "

-AJC', '<p>This gear was used in 1 project (LHA_95_013).  No catch was reported for the samples that used this gear code. There is no indication on gear length  or material.</p>
<p>***After meeting (03/27/2017 with C. Davis, S. Currie, A. Cottril, and A.Conway) to discuss gear codes. GL15, GL20, and GL25 will be the GR used for FLINs and SLINs moving forward. This means projects using this "GL20" will need to be identified and assigned a new code if they do not conform to the configuration listed below:</p>
<p>A GL20 is 3 panels of 51mm mesh. Length: 45.7m</p>
<p>From SLIN manual:</p>
<p>"The standard gear is 3 mesh sizes of monofilament gillnet, made in Finland according to the specifications that were established by the B.C. Ministry of the Environmnet. The configuration is a 91.4m (300ft) gillnet gang, comprised of six 15.2m (50ft) X 2.4 (8ft) panels tied together with the brail loops. All six panels per gang are of the same mesh size, either 38mm (1.5 in), 51mm (2.5 in), or 65mm (2.5 in) stretched mesh. The nets, referred to as "monofilament research gillnets" are available from two Canadian distributors. "</p>
<p>-AJC</p>', false, false, NULL);
INSERT INTO fn_portal_gear VALUES (216, 7, 'Unknown Gill Net!', 'GL15', 3, 273, 'This gear was used in 4 projects (LHA_IS93_013, LHA_IS94_013, LHA_IS95_013, LHA_IA89_009).  No information is currently available on this gear for the *013 projects.  For the 009 project, the gear consisted of 3 91m panels of unknown mesh size (eff= 641, 642, 643??).

***After meeting (03/27/2017 with C. Davis, S. Currie, A. Cottril, and A.Conway) to discuss gear codes. GL15, GL20, and GL25 will be the GR used for FLINs and SLINs moving forward. This means projects using this "GL15" will need to be identified and assigned a new code if they do not conform to the configuration listed below:

A GL15 is 3 panels of 38mm mesh. Length: 45.7m

From SLIN manual (Found here: http://142.143.160.56:8080/projects/projectdetail/lhr_ia03_119/):

"The standard gear is 3 mesh sizes of monofilament gillnet, made in Finland according to the specifications that were established by the B.C. Ministry of the Environmnet. The configuration is a 91.4m (300ft) gillnet gang, comprised of six 15.2m (50ft) X 2.4 (8ft) panels tied together with the brail loops. All six panels per gang are of the same mesh size, either 38mm (1.5 in), 51mm (2.5 in), or 65mm (2.5 in) stretched mesh. The nets, referred to as "monofilament research gillnets" are available from two Canadian distributors. "

-AJC', '<p>This gear was used in 4 projects (LHA_IS93_013, LHA_IS94_013, LHA_IS95_013, LHA_IA89_009).  No information is currently available on this gear for the *013 projects.  For the 009 project, the gear consisted of 3 91m panels of unknown mesh size (eff= 641, 642, 643??).</p>
<p>***After meeting (03/27/2017 with C. Davis, S. Currie, A. Cottril, and A.Conway) to discuss gear codes. GL15, GL20, and GL25 will be the GR used for FLINs and SLINs moving forward. This means projects using this "GL15" will need to be identified and assigned a new code if they do not conform to the configuration listed below:</p>
<p>A GL15 is 3 panels of 38mm mesh. Length: 45.7m</p>
<p>From SLIN manual (Found here: http://142.143.160.56:8080/projects/projectdetail/lhr_ia03_119/):</p>
<p>"The standard gear is 3 mesh sizes of monofilament gillnet, made in Finland according to the specifications that were established by the B.C. Ministry of the Environmnet. The configuration is a 91.4m (300ft) gillnet gang, comprised of six 15.2m (50ft) X 2.4 (8ft) panels tied together with the brail loops. All six panels per gang are of the same mesh size, either 38mm (1.5 in), 51mm (2.5 in), or 65mm (2.5 in) stretched mesh. The nets, referred to as "monofilament research gillnets" are available from two Canadian distributors. "</p>
<p>-AJC</p>', false, false, NULL);


--
-- Name: fn_portal_gear_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cottrillad
--

SELECT pg_catalog.setval('fn_portal_gear_id_seq', 263, true);


--
-- PostgreSQL database dump complete
--

